### TO Get All Companies
GET http://localhost:3030/company
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoyLCJpc19zdXBlcl9hZG1pbiI6ZmFsc2UsImZpcnN0bmFtZSI6ImpvaG4iLCJsYXN0bmFtZSI6Im5hdGFjaGEiLCJyb2xlIjoiQ0xJRU5UX0FETUlOIiwicm9sZV9sZXZlbCI6MTB9LCJpYXQiOjE2Njk0NTgxNjAsImV4cCI6MTY2OTQ2ODk2MH0.s_Y3JobGUKYt0aDOQloxu8CrvWvAJ89dCOZv4tX0Xcw


### To Get A Company
GET http://localhost:3030/company/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoyLCJpc19zdXBlcl9hZG1pbiI6ZmFsc2UsImZpcnN0bmFtZSI6ImpvaG4iLCJsYXN0bmFtZSI6Im5hdGFjaGEiLCJyb2xlIjoiQ0xJRU5UX0FETUlOIiwicm9sZV9sZXZlbCI6MTB9LCJpYXQiOjE2Njk0NTgxNjAsImV4cCI6MTY2OTQ2ODk2MH0.s_Y3JobGUKYt0aDOQloxu8CrvWvAJ89dCOZv4tX0Xcw



### To Create A New Company
POST  http://localhost:3030/company
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoyLCJpc19zdXBlcl9hZG1pbiI6ZmFsc2UsImZpcnN0bmFtZSI6ImpvaG4iLCJsYXN0bmFtZSI6Im5hdGFjaGEiLCJyb2xlIjoiQ0xJRU5UX0FETUlOIiwicm9sZV9sZXZlbCI6MTB9LCJpYXQiOjE2Njk0NTgxNjAsImV4cCI6MTY2OTQ2ODk2MH0.s_Y3JobGUKYt0aDOQloxu8CrvWvAJ89dCOZv4tX0Xcw

{
    "name": "ORANGE"
}


### To Update A Company
PUT  http://localhost:3030/company/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoyLCJpc19zdXBlcl9hZG1pbiI6ZmFsc2UsImZpcnN0bmFtZSI6ImpvaG4iLCJsYXN0bmFtZSI6Im5hdGFjaGEiLCJyb2xlIjoiQ0xJRU5UX0FETUlOIiwicm9sZV9sZXZlbCI6MTB9LCJpYXQiOjE2Njk0NTgxNjAsImV4cCI6MTY2OTQ2ODk2MH0.s_Y3JobGUKYt0aDOQloxu8CrvWvAJ89dCOZv4tX0Xcw

{
    "name": "BANANA_2"
}


### To Delete A Company
DELETE   http://localhost:3030/company/12221
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoyLCJpc19zdXBlcl9hZG1pbiI6ZmFsc2UsImZpcnN0bmFtZSI6ImpvaG4iLCJsYXN0bmFtZSI6Im5hdGFjaGEiLCJyb2xlIjoiQ0xJRU5UX0FETUlOIiwicm9sZV9sZXZlbCI6MTB9LCJpYXQiOjE2Njk0NTgxNjAsImV4cCI6MTY2OTQ2ODk2MH0.s_Y3JobGUKYt0aDOQloxu8CrvWvAJ89dCOZv4tX0Xcw


### To Create A New ClientAdmin And Add to Company
POST    http://localhost:3030/company/1/admin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoyLCJpc19zdXBlcl9hZG1pbiI6ZmFsc2UsImZpcnN0bmFtZSI6ImpvaG4iLCJsYXN0bmFtZSI6Im5hdGFjaGEiLCJyb2xlIjoiQ0xJRU5UX0FETUlOIiwicm9sZV9sZXZlbCI6MTB9LCJpYXQiOjE2Njk0NTgxNjAsImV4cCI6MTY2OTQ2ODk2MH0.s_Y3JobGUKYt0aDOQloxu8CrvWvAJ89dCOZv4tX0Xcw

{
    "username": "clientadmin2",
    "password": "clientadmin2_123",
    "firstname": "jonb",
    "lastname": "jonbnb"
}


### To Add Existing ClientAdmin To Company
POST    http://localhost:3030/company/3/admin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoyLCJpc19zdXBlcl9hZG1pbiI6ZmFsc2UsImZpcnN0bmFtZSI6ImpvaG4iLCJsYXN0bmFtZSI6Im5hdGFjaGEiLCJyb2xlIjoiQ0xJRU5UX0FETUlOIiwicm9sZV9sZXZlbCI6MTB9LCJpYXQiOjE2Njk0NTgxNjAsImV4cCI6MTY2OTQ2ODk2MH0.s_Y3JobGUKYt0aDOQloxu8CrvWvAJ89dCOZv4tX0Xcw

{
    "id": "2"
}