### TO Get All Companies
GET http://localhost:3030/company
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoxLCJpc1N1cGVyQWRtaW4iOnRydWUsImZpcnN0bmFtZSI6InNhbGFyeSIsImxhc3RuYW1lIjoiaGVybyIsInJvbGUiOiJTVVBFUl9BRE1JTiIsInJvbGVMZXZlbCI6MX0sImlhdCI6MTY2OTQ3MzcwMSwiZXhwIjoxNjY5NDg0NTAxfQ.Jla7M0bBACndhDwgWOhluWdouiUUlnqKSGaVipjJeoE


### To Get A Company
GET http://localhost:3030/company/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoxLCJpc1N1cGVyQWRtaW4iOnRydWUsImZpcnN0bmFtZSI6InNhbGFyeSIsImxhc3RuYW1lIjoiaGVybyIsInJvbGUiOiJTVVBFUl9BRE1JTiIsInJvbGVMZXZlbCI6MX0sImlhdCI6MTY2OTQ3MzcwMSwiZXhwIjoxNjY5NDg0NTAxfQ.Jla7M0bBACndhDwgWOhluWdouiUUlnqKSGaVipjJeoE



### To Create A New Company
POST  http://localhost:3030/company
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoxLCJpc1N1cGVyQWRtaW4iOnRydWUsImZpcnN0bmFtZSI6InNhbGFyeSIsImxhc3RuYW1lIjoiaGVybyIsInJvbGUiOiJTVVBFUl9BRE1JTiIsInJvbGVMZXZlbCI6MX0sImlhdCI6MTY2OTQ3MzcwMSwiZXhwIjoxNjY5NDg0NTAxfQ.Jla7M0bBACndhDwgWOhluWdouiUUlnqKSGaVipjJeoE

{
    "name": "ORANGE"
}


### To Update A Company
PUT  http://localhost:3030/company/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoxLCJpc1N1cGVyQWRtaW4iOnRydWUsImZpcnN0bmFtZSI6InNhbGFyeSIsImxhc3RuYW1lIjoiaGVybyIsInJvbGUiOiJTVVBFUl9BRE1JTiIsInJvbGVMZXZlbCI6MX0sImlhdCI6MTY2OTQ3MzcwMSwiZXhwIjoxNjY5NDg0NTAxfQ.Jla7M0bBACndhDwgWOhluWdouiUUlnqKSGaVipjJeoE

{
    "name": "ORANGE_2"
}


### To Delete A Company
DELETE   http://localhost:3030/company/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoxLCJpc1N1cGVyQWRtaW4iOnRydWUsImZpcnN0bmFtZSI6InNhbGFyeSIsImxhc3RuYW1lIjoiaGVybyIsInJvbGUiOiJTVVBFUl9BRE1JTiIsInJvbGVMZXZlbCI6MX0sImlhdCI6MTY2OTQ3MzcwMSwiZXhwIjoxNjY5NDg0NTAxfQ.Jla7M0bBACndhDwgWOhluWdouiUUlnqKSGaVipjJeoE


### To Create A New ClientAdmin And Add to Company
POST    http://localhost:3030/company/1/admin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoxLCJpc1N1cGVyQWRtaW4iOnRydWUsImZpcnN0bmFtZSI6InNhbGFyeSIsImxhc3RuYW1lIjoiaGVybyIsInJvbGUiOiJTVVBFUl9BRE1JTiIsInJvbGVMZXZlbCI6MX0sImlhdCI6MTY2OTQ3MzcwMSwiZXhwIjoxNjY5NDg0NTAxfQ.Jla7M0bBACndhDwgWOhluWdouiUUlnqKSGaVipjJeoE

{
    "username": "clientadmin5",
    "password": "clientadmin5_123",
    "firstname": "jonb",
    "lastname": "jonbnb"
}


### To Add Existing ClientAdmin To Company
POST    http://localhost:3030/company/2/admin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoxLCJpc1N1cGVyQWRtaW4iOnRydWUsImZpcnN0bmFtZSI6InNhbGFyeSIsImxhc3RuYW1lIjoiaGVybyIsInJvbGUiOiJTVVBFUl9BRE1JTiIsInJvbGVMZXZlbCI6MX0sImlhdCI6MTY2OTQ3MzcwMSwiZXhwIjoxNjY5NDg0NTAxfQ.Jla7M0bBACndhDwgWOhluWdouiUUlnqKSGaVipjJeoE

{
    "id": "11"
}