### Get all company
GET http://localhost:3030/company
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoxLCJpc19zdXBlcl9hZG1pbiI6dHJ1ZSwiZmlyc3RuYW1lIjoic2FsYXJ5IiwibGFzdG5hbWUiOiJoZXJvIiwicm9sZSI6IlNVUEVSX0FETUlOIiwicm9sZV9sZXZlbCI6MX0sImlhdCI6MTY2OTQ0NjI2MywiZXhwIjoxNjY5NDU3MDYzfQ.Tq6hgh7Y4KiEYhgLYP7H8SSfNdS4eU_ZQe37DCLBMfA


### Get a company
GET http://localhost:3030/company/9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoxLCJpc19zdXBlcl9hZG1pbiI6dHJ1ZSwiZmlyc3RuYW1lIjoic2FsYXJ5IiwibGFzdG5hbWUiOiJoZXJvIiwicm9sZSI6IlNVUEVSX0FETUlOIiwicm9sZV9sZXZlbCI6MX0sImlhdCI6MTY2OTQ0NjI2MywiZXhwIjoxNjY5NDU3MDYzfQ.Tq6hgh7Y4KiEYhgLYP7H8SSfNdS4eU_ZQe37DCLBMfA



### Create new company
POST  http://localhost:3030/company
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoxLCJpc19zdXBlcl9hZG1pbiI6dHJ1ZSwiZmlyc3RuYW1lIjoic2FsYXJ5IiwibGFzdG5hbWUiOiJoZXJvIiwicm9sZSI6IlNVUEVSX0FETUlOIiwicm9sZV9sZXZlbCI6MX0sImlhdCI6MTY2OTQ0NjI2MywiZXhwIjoxNjY5NDU3MDYzfQ.Tq6hgh7Y4KiEYhgLYP7H8SSfNdS4eU_ZQe37DCLBMfA

{
    "name": "AINGLY"
}


### Update a company
PUT  http://localhost:3030/company/11
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoxLCJpc19zdXBlcl9hZG1pbiI6dHJ1ZSwiZmlyc3RuYW1lIjoic2FsYXJ5IiwibGFzdG5hbWUiOiJoZXJvIiwicm9sZSI6IlNVUEVSX0FETUlOIiwicm9sZV9sZXZlbCI6MX0sImlhdCI6MTY2OTQ0NjI2MywiZXhwIjoxNjY5NDU3MDYzfQ.Tq6hgh7Y4KiEYhgLYP7H8SSfNdS4eU_ZQe37DCLBMfA

{
    "name": "AINGLY_2"
}


### Delete a company
DELETE   http://localhost:3030/company/11
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoxLCJpc19zdXBlcl9hZG1pbiI6dHJ1ZSwiZmlyc3RuYW1lIjoic2FsYXJ5IiwibGFzdG5hbWUiOiJoZXJvIiwicm9sZSI6IlNVUEVSX0FETUlOIiwicm9sZV9sZXZlbCI6MX0sImlhdCI6MTY2OTQ0NjI2MywiZXhwIjoxNjY5NDU3MDYzfQ.Tq6hgh7Y4KiEYhgLYP7H8SSfNdS4eU_ZQe37DCLBMfA

