### GET me
GET http://localhost:3030/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoyLCJpc1N1cGVyQWRtaW4iOmZhbHNlLCJmaXJzdG5hbWUiOiJqb2huIiwibGFzdG5hbWUiOiJuYXRhY2hhIiwicm9sZSI6IkNMSUVOVF9BRE1JTiIsInJvbGVMZXZlbCI6MTB9LCJpYXQiOjE2Njk0NzM2MzAsImV4cCI6MTY2OTQ4NDQzMH0.aEu67Zy4x2elHOU5lPAfu3Um5fF3h5wInPlcAze9czo