### GET me
GET http://localhost:3000/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjozLCJpc1N1cGVyQWRtaW4iOmZhbHNlLCJmaXJzdG5hbWUiOiJhcHBsZV9lbXBsb3llZTFfZiIsImxhc3RuYW1lIjoiYXBwbGVfZW1wbG95ZWUxX2wiLCJyb2xlIjoiRU1QTE9ZRUUiLCJyb2xlTGV2ZWwiOjEwMH0sImlhdCI6MTY2OTU2Njk1OCwiZXhwIjoxNjY5NTc3NzU4fQ.UV-CU61Kkef0VtXfGk7o7VzoyhrDDvoh-w5t1TVSKhM