### GET me
GET http://localhost:3001/superadmin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoxLCJpc19zdXBlcl9hZG1pbiI6dHJ1ZSwiZmlyc3RuYW1lIjoic2FsYXJ5IiwibGFzdG5hbWUiOiJoZXJvIiwicm9sZV9sZXZlbCI6MX0sImlhdCI6MTY2OTMwOTAyMCwiZXhwIjoxNjY5MzA5MDM1fQ.PNKZLLVjMCfxWVOjyktqzrhStY5Lu1jrX9RkdVbaLPo