### To Create Transfer
POST http://localhost:3000/company/1/transfer
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjozLCJpc1N1cGVyQWRtaW4iOmZhbHNlLCJmaXJzdG5hbWUiOiJhcHBsZV9lbXBsb3llZTFfZiIsImxhc3RuYW1lIjoiYXBwbGVfZW1wbG95ZWUxX2wiLCJyb2xlIjoiRU1QTE9ZRUUiLCJyb2xlTGV2ZWwiOjEwMH0sImlhdCI6MTY2OTY0NjY5NiwiZXhwIjoxNjY5NjU3NDk2fQ.W4H83075GuzjFKqFnTlxlHHasYgTlAcb8ZQhSzVqSZg

{
    "amount": 1,
    "date": "2022-12-10"
}

