### To Create Transfer
POST http://localhost:3000/company/2/transfer
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoxMSwiaXNTdXBlckFkbWluIjpmYWxzZSwiZmlyc3RuYW1lIjoiYzJfZW1wbG95ZWUzX2YiLCJsYXN0bmFtZSI6ImMyX2VtcGxveWVlM19sIiwicm9sZSI6IkVNUExPWUVFIiwicm9sZUxldmVsIjoxMDB9LCJpYXQiOjE2Njk2NTE2MDIsImV4cCI6MTY2OTY2MjQwMn0.nrZX5u2khyzW9BJDnbYgePmo4nzVIizj7vpda8tmvG4

{
    "amount": 20000,
    "date": "2022-12-10"
}

