### Signin
POST http://localhost:3000/signin
Content-Type: application/json

{
    "username": "doretta",
    "password": "doretta123"
}

# salaryhero
# username: salaryhero
# password: salaryhero123

# mock clientAdmin
# username: admin
# password: admin123

# mock employee of APPLE company
# username: doretta
# password: doretta123