### Signin
POST http://localhost:3000/signin
Content-Type: application/json

{
    "username": "c2_employee3",
    "password": "c2_employee3_123"
}

# salaryhero
# username: salaryhero
# password: salaryhero_123

# mock clientAdmin of APPLE company
# username: apple_admin1
# password: apple_admin1_123

# mock employee of APPLE company
# username: apple_employee1
# password: apple_employee1_123