### TO Get All Companies
GET http://localhost:3030/employee?companyId=3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoyLCJpc19zdXBlcl9hZG1pbiI6ZmFsc2UsImZpcnN0bmFtZSI6ImpvaG4iLCJsYXN0bmFtZSI6Im5hdGFjaGEiLCJyb2xlIjoiQ0xJRU5UX0FETUlOIiwicm9sZV9sZXZlbCI6MTB9LCJpYXQiOjE2Njk0Njg5NjcsImV4cCI6MTY2OTQ3OTc2N30.CpFe3y-1aaPutIMPb-WTgEVlc06Ayu1SrcCxvB2-NCo


### To Get A Company
GET http://localhost:3030/company/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoyLCJpc19zdXBlcl9hZG1pbiI6ZmFsc2UsImZpcnN0bmFtZSI6ImpvaG4iLCJsYXN0bmFtZSI6Im5hdGFjaGEiLCJyb2xlIjoiQ0xJRU5UX0FETUlOIiwicm9sZV9sZXZlbCI6MTB9LCJpYXQiOjE2Njk0Njg5NjcsImV4cCI6MTY2OTQ3OTc2N30.CpFe3y-1aaPutIMPb-WTgEVlc06Ayu1SrcCxvB2-NCo

