### This API Require [CLIENT_ADMIN OR SUPER_ADMIN] !!!


### TO Get All Employees in Company
GET http://localhost:3000/company/2/employee
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjo2LCJpc1N1cGVyQWRtaW4iOmZhbHNlLCJmaXJzdG5hbWUiOiJjMl9hZG1pbjFfZiIsImxhc3RuYW1lIjoiYzJfYWRtaW4xX2wiLCJyb2xlIjoiQ0xJRU5UX0FETUlOIiwicm9sZUxldmVsIjoxMH0sImlhdCI6MTY2OTY1MTM5NiwiZXhwIjoxNjY5NjYyMTk2fQ.Rf4w4gRdv_KqU-BfK_VTmOqWpa-kSDaYsRgNgBhpLGo


### TO Get A Employee in Company
GET http://localhost:3000/company/2/employee?employeeId=6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjo2LCJpc1N1cGVyQWRtaW4iOmZhbHNlLCJmaXJzdG5hbWUiOiJjMl9hZG1pbjFfZiIsImxhc3RuYW1lIjoiYzJfYWRtaW4xX2wiLCJyb2xlIjoiQ0xJRU5UX0FETUlOIiwicm9sZUxldmVsIjoxMH0sImlhdCI6MTY2OTY1MTM5NiwiZXhwIjoxNjY5NjYyMTk2fQ.Rf4w4gRdv_KqU-BfK_VTmOqWpa-kSDaYsRgNgBhpLGo


### To Create a New Employee For A Company
POST http://localhost:3000/company/2/employee
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjo2LCJpc1N1cGVyQWRtaW4iOmZhbHNlLCJmaXJzdG5hbWUiOiJjMl9hZG1pbjFfZiIsImxhc3RuYW1lIjoiYzJfYWRtaW4xX2wiLCJyb2xlIjoiQ0xJRU5UX0FETUlOIiwicm9sZUxldmVsIjoxMH0sImlhdCI6MTY2OTY1MTM5NiwiZXhwIjoxNjY5NjYyMTk2fQ.Rf4w4gRdv_KqU-BfK_VTmOqWpa-kSDaYsRgNgBhpLGo

{
    "username": "c2_employee3",
    "password": "c2_employee3_123",
    "firstname": "c2_employee3_f",
    "lastname": "c2_employee3_l",
    "baseSalary": 35000
}


### To Update A Employee For A Company (can update some fileds)
PUT http://localhost:3000/company/2/employee/6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjo2LCJpc1N1cGVyQWRtaW4iOmZhbHNlLCJmaXJzdG5hbWUiOiJjMl9hZG1pbjFfZiIsImxhc3RuYW1lIjoiYzJfYWRtaW4xX2wiLCJyb2xlIjoiQ0xJRU5UX0FETUlOIiwicm9sZUxldmVsIjoxMH0sImlhdCI6MTY2OTY1MTM5NiwiZXhwIjoxNjY5NjYyMTk2fQ.Rf4w4gRdv_KqU-BfK_VTmOqWpa-kSDaYsRgNgBhpLGo

{
    "baseSalary": 50000
}


### To Delete A Employee
DELETE http://localhost:3000/company/1/employee/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjo2LCJpc1N1cGVyQWRtaW4iOmZhbHNlLCJmaXJzdG5hbWUiOiJjMl9hZG1pbjFfZiIsImxhc3RuYW1lIjoiYzJfYWRtaW4xX2wiLCJyb2xlIjoiQ0xJRU5UX0FETUlOIiwicm9sZUxldmVsIjoxMH0sImlhdCI6MTY2OTY1MTM5NiwiZXhwIjoxNjY5NjYyMTk2fQ.Rf4w4gRdv_KqU-BfK_VTmOqWpa-kSDaYsRgNgBhpLGo


### To Import Employees For A Company
POST http://localhost:3000/company/2/employee/import
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjo2LCJpc1N1cGVyQWRtaW4iOmZhbHNlLCJmaXJzdG5hbWUiOiJjMl9hZG1pbjFfZiIsImxhc3RuYW1lIjoiYzJfYWRtaW4xX2wiLCJyb2xlIjoiQ0xJRU5UX0FETUlOIiwicm9sZUxldmVsIjoxMH0sImlhdCI6MTY2OTY1MTM5NiwiZXhwIjoxNjY5NjYyMTk2fQ.Rf4w4gRdv_KqU-BfK_VTmOqWpa-kSDaYsRgNgBhpLGo

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="employees.mock.csv"

< ./employees.mock.csv
------WebKitFormBoundary7MA4YWxkTrZu0gW--
