### TO Get All Employees in Company
GET http://localhost:3030/company/1/employee
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoxLCJpc1N1cGVyQWRtaW4iOnRydWUsImZpcnN0bmFtZSI6InNhbGFyeSIsImxhc3RuYW1lIjoiaGVybyIsInJvbGUiOiJTVVBFUl9BRE1JTiIsInJvbGVMZXZlbCI6MX0sImlhdCI6MTY2OTUxNzcyNywiZXhwIjoxNjY5NTI4NTI3fQ.G-Pqsjw0VVjizBthH0boafocWtgHLECEnaNWPwH_7KU


### TO Get A Employee in Company
GET http://localhost:3030/company/2/employee?employeeId=1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoxLCJpc1N1cGVyQWRtaW4iOnRydWUsImZpcnN0bmFtZSI6InNhbGFyeSIsImxhc3RuYW1lIjoiaGVybyIsInJvbGUiOiJTVVBFUl9BRE1JTiIsInJvbGVMZXZlbCI6MX0sImlhdCI6MTY2OTUxNzcyNywiZXhwIjoxNjY5NTI4NTI3fQ.G-Pqsjw0VVjizBthH0boafocWtgHLECEnaNWPwH_7KU


### To Create a New Employee For A Company
POST http://localhost:3030/company/2/employee
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoxLCJpc1N1cGVyQWRtaW4iOnRydWUsImZpcnN0bmFtZSI6InNhbGFyeSIsImxhc3RuYW1lIjoiaGVybyIsInJvbGUiOiJTVVBFUl9BRE1JTiIsInJvbGVMZXZlbCI6MX0sImlhdCI6MTY2OTUxNzcyNywiZXhwIjoxNjY5NTI4NTI3fQ.G-Pqsjw0VVjizBthH0boafocWtgHLECEnaNWPwH_7KU

{
    "username": "employee2",
    "password": "employee2_123",
    "firstname": "employee2_f",
    "lastname": "employee2_l",
    "baseSalary": 12500
}


### To Update A Employee For A Company
PUT http://localhost:3030/company/1/employee/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoxLCJpc1N1cGVyQWRtaW4iOnRydWUsImZpcnN0bmFtZSI6InNhbGFyeSIsImxhc3RuYW1lIjoiaGVybyIsInJvbGUiOiJTVVBFUl9BRE1JTiIsInJvbGVMZXZlbCI6MX0sImlhdCI6MTY2OTUxNzcyNywiZXhwIjoxNjY5NTI4NTI3fQ.G-Pqsjw0VVjizBthH0boafocWtgHLECEnaNWPwH_7KU

{
    "username": "employee1",
    "password": "employee1_123",
    "firstname": "employee1_fistname",
    "lastname": "employee1_lastname",
    "baseSalary": 12355555
}


### To Delete A Employee
DELETE  http://localhost:3030/company/1/employee/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoxLCJpc1N1cGVyQWRtaW4iOnRydWUsImZpcnN0bmFtZSI6InNhbGFyeSIsImxhc3RuYW1lIjoiaGVybyIsInJvbGUiOiJTVVBFUl9BRE1JTiIsInJvbGVMZXZlbCI6MX0sImlhdCI6MTY2OTUxNzcyNywiZXhwIjoxNjY5NTI4NTI3fQ.G-Pqsjw0VVjizBthH0boafocWtgHLECEnaNWPwH_7KU

